name: string_normalizer
description: Helps you remove accents and diacritics from strings. It comes with a built-in Crawler feature.
version: 0.3.5
homepage: https://github.com/lamnhan066/string_normalizer
topics:
  - normalize
  - unicode
  - accents
  - diacritics

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  characters: ^1.3.0

dev_dependencies:
  test: ^1.25.5
  lints: ^4.0.0
  dart_style: ^2.3.6
  http: ^1.1.2
